FROM python:3.10.6-slim

RUN pip install pipenv

WORKDIR /app

COPY Pipfile* ./

RUN pipenv install --system --deploy

COPY flask_script.py *.pkl ./

EXPOSE 9696

ENTRYPOINT gunicorn --bind 0.0.0.0:9696 flask_script:app
