FROM python:3.10.6-slim

RUN pip install pipenv

WORKDIR /app

COPY Pipfile* ./

RUN pipenv install --system --deploy

COPY flask_script.py *.pkl ./

EXPOSE 8000

ENTRYPOINT gunicorn --bind 0.0.0.0:8000 flask_script:app
